# Generated by Django 4.1.4 on 2023-02-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='apartment',
            field=models.CharField(default='', max_length=15, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='building',
            field=models.CharField(default='', max_length=15, verbose_name='Строение'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='house',
            field=models.CharField(max_length=15, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='structure',
            field=models.CharField(default='', max_length=15, verbose_name='Корпус'),
        ),
    ]
