# Generated by Django 4.1.4 on 2023-02-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_contact_apartment_alter_contact_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='apartment',
            field=models.CharField(blank=True, max_length=15, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='building',
            field=models.CharField(blank=True, max_length=15, verbose_name='Строение'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='structure',
            field=models.CharField(blank=True, max_length=15, verbose_name='Корпус'),
        ),
    ]
